name: "Integration Tests"

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  go-tests:
    name: "Run Go Integration Test"
    runs-on: ubuntu-latest

    steps:
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13.2
          #          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15.3
      - uses: actions/checkout@v2
      - name: Download Go Modules
        working-directory: test
        run: go mod init github.com/3ll34ndr0/gh-actions-test
      - name: List directory 
        run: ls -lha ./ && ls -lha test/
      - name: Run Go Tests
        working-directory: test
        run: go test -v
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

           
